force-app/main/default/objects/LLC_BI__Loan__c/LLC_BI__Loan__c.object-meta.xml
<CustomObject>
    <description>The Loan Object stores information of the details of a Loan.</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/LLC_BI__Loan__c/fields/LLC_BI__lookupKey__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI__lookupKey__c</fullName>
    <description>The loan number is an external, unique key for this loan. This field is used when syncing nCino with the financial institution&apos;s core.</description>
    <externalId>true</externalId>
    <label>Loan Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentScanControllerTest.cls
@isTest
private class DocumentScanControllerTest {
  @TestSetup
  static void makeData() {
    //* Create loans
    List<LLC_BI__Loan__c> testLoans = new List<LLC_BI__Loan__c>();

    LLC_BI__Loan__c testLoan = new LLC_BI__Loan__c();
    testLoan.Name = 'test loan 1';
    testLoan.LLC_BI__lookupKey__c = '1234';
    testLoans.add(testLoan);

    insert testLoans;
  }

  @isTest
  static void testQueryLoans() {
    System.debug('hello');
    List<LLC_BI__Loan__c> matchingLoans = DocumentScanController.queryLoans(
      '1234'
    );
    System.assertNotEquals(0, matchingLoans.size());
  }
}