force-app/main/default/objects/Lead/fields/LLC_BI__Loan__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI__Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is auto-populated as a look up to a loan created when Convert to nCino is selected on the lead. This allows the financial institution and the BI tool to track converted leads</description>
    <label>Converted Lead</label>
    <referenceTo>LLC_BI__Loan__c</referenceTo>
    <relationshipLabel>Converted Lead</relationshipLabel>
    <relationshipName>ConvertedLead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LLC_BI__Loan__c/LLC_BI__Loan__c.object-meta.xml
<CustomObject>
    <description>The Loan Object stores information of the details of a Loan.</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/LLC_BI__LoanTeam__c/LLC_BI__LoanTeam__c.object-meta.xml
<CustomObject>
    <description>The Loan Team Member object captures information about the loan teams assigned to loans in nCino.</description>
    <label>Loan Team Member</label>
    <nameField>
        <displayFormat>LT-{00000000}</displayFormat>
        <label>Loan Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LLC_BI__LoanTeam__c/fields/LLC_BI__Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI__Assigned_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required. It is manually populated. It identifies the role that has been assigned to a user when adding them to the loan team.</description>
    <inlineHelpText>Available Roles: Loan Officer; Lending Assistant; Credit Analyst / Underwriter; Doc Prep Processor; Loan Ops.</inlineHelpText>
    <label>Role</label>
    <referenceTo>LLC_BI__Role__c</referenceTo>
    <relationshipLabel>Loan Team Members</relationshipLabel>
    <relationshipName>Loan_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LLC_BI__LoanTeam__c/fields/LLC_BI__Loan__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI__Loan__c</fullName>
    <description>This field is a master detail field, used to specify the loan that the loan team is associated to.</description>
    <label>Loan</label>
    <referenceTo>LLC_BI__Loan__c</referenceTo>
    <relationshipLabel>Loan Team Members</relationshipLabel>
    <relationshipName>Loan_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LLC_BI__LoanTeam__c/fields/LLC_BI__User__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a look up to an nCino user that will be assigned a role, and associated to the loan team.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loan_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecordAssignConfiguration__c/RecordAssignConfiguration__c.object-meta.xml
<CustomObject>
    <description>Configuration object for record assignment rules</description>
    <label>Record Assignment Configuration</label>
    <nameField>
        <displayFormat>RAC-{0000}</displayFormat>
        <label>Record Assignment Configuration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Assignment Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecordAssignConfiguration__c/fields/Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Name__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique name that will trigger record assignment (e.g. when the name listed here matches a Queue set as the owner of a record it will trigger the assignment process).</inlineHelpText>
    <label>Queue Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/RecordAssignMember__c.object-meta.xml
<CustomObject>
    <description>Configuration object for record assignment rules</description>
    <label>Record Assignment Member</label>
    <nameField>
        <displayFormat>RAM-{0000}</displayFormat>
        <label>Record Assignment Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Assignment Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecordAssignMember__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Only Active members are considered and assigned</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/Last_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment__c</fullName>
    <inlineHelpText>Date and time of last assignment from the round robin process</inlineHelpText>
    <label>Last Assignment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/Limit_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Limit_Frequency__c</fullName>
    <inlineHelpText>Length of time in which a specified limit will be enforced</inlineHelpText>
    <label>Limit Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/RecordAssignConfiguration__c.field-meta.xml
<CustomField>
    <fullName>RecordAssignConfiguration__c</fullName>
    <label>Record Assignment Configuration</label>
    <referenceTo>RecordAssignConfiguration__c</referenceTo>
    <relationshipLabel>Record Assignment Members</relationshipLabel>
    <relationshipName>RecordAssignMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/Records_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Records_Assigned__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of records assigned during the specified Limit Frequency</inlineHelpText>
    <label>Records Assigned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/Under_Limit__c.field-meta.xml
<CustomField>
    <fullName>Under_Limit__c</fullName>
    <formula>OR(ISBLANK(Limit__c), Records_Assigned__c &lt; Limit__c)</formula>
    <label>Under Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecordAssignMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user that will be assigned as an owner from the round robin process</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoanRoundRobinAssignInvocable.cls
/**
 * Invocable apex class for configurable round robin record assignment
 */
global without sharing class LoanRoundRobinAssignInvocable {
    
    /**
     * Bulkified round robin assignment of records driven off of Record Assignment Configurations tied to Queues
     */
    @InvocableMethod(label='Assign Loan Team Members' description='Perform round robin record assignment for Loan Team Members')
    global static void assignLoanTeam(List<AssignmentRequest> requests) {
        if (requests != null && !requests.isEmpty()) {
            //preprocessing of any members over limit
            processMemberLimits();

            //collect request info
            Set<String> queueNames = new Set<String>();
            List<Id> recordIds = new List<Id>();
            List<Id> roleIds = new List<Id>();
            Map<Id,String> recordIdQueueNameMap = new Map<Id,String>();
            Map<Id,Id> recordIdRoleIdMap = new Map<Id,Id>();
            for (AssignmentRequest r : requests) {
                recordIds.add(r.recordId);
                if (String.isNotBlank(r.queueName)) {
                    queueNames.add(r.queueName);
                    recordIdQueueNameMap.put(r.recordId, r.queueName);
                }
                if (String.isNotBlank(r.teamRole)) {
                    roleIds.add(r.teamRole);
                    recordIdQueueNameMap.put(r.recordId, r.teamRole);
                }
            }

            //determine sobject type, dynamic query record owners
            String sobjType = recordIds[0].getSObjectType().getDescribe().getName();
            List<SObject> recordsToAssign = Database.query('SELECT Id, OwnerId, Owner.Name FROM '+sobjType+' WHERE Id IN :recordIds');

            //Get available queues that could be record owner
            Map<Id,String> queueIdNameMap = new Map<Id,String>();
            for (QueueSobject queueType : [SELECT Id, QueueId, Queue.Name FROM QueueSobject WHERE SObjectType = :sobjType]) {
                queueIdNameMap.put(queueType.QueueId, queueType.Queue.Name);
            }
            //collect queue names on records with queue owner
            for (SObject r : recordsToAssign) {
                if (queueIdNameMap.containsKey((Id)r.get('OwnerId'))) {
                    queueNames.add(queueIdNameMap.get((Id)r.get('OwnerId')));
                }
            }

            //get matching round robin configs with next assignees
            List<RecordAssignConfiguration__c> rrConfigs = [
                SELECT Id, Queue_Name__c, 
                    (SELECT Id, User__c, Records_Assigned__c 
                        FROM RecordAssignMembers__r AS m
                        WHERE Active__c = true AND User__r.IsActive = true AND Under_Limit__c = true
                        ORDER BY Last_Assignment__c ASC NULLS FIRST, Records_Assigned__c ASC NULLS FIRST
                    )
                FROM RecordAssignConfiguration__c 
                WHERE Queue_Name__c IN :queueNames
            ];

            //process records with round robin configs
            if (!rrConfigs.isEmpty()) {
                //Map queue name to the config
                Map<String,RecordAssignConfiguration__c> queueNameToConfig = new Map<String,RecordAssignConfiguration__c>();
                for (RecordAssignConfiguration__c config : rrConfigs) {
                    queueNameToConfig.put(config.Queue_Name__c, config);
                }

                //run through the records and assign by config
                Map<Id, RecordAssignMember__c> userIdToMember = new Map<Id, RecordAssignMember__c>();
                List<SObject> recordsToUpdate = new List<SObject>();
                List<SObject> recordsToCreate = new List<SObject>();
                Map<String,Integer> queueNameToRouteIndex = new Map<String,Integer>();
                for (SObject record : recordsToAssign) { 
                    //determine queue name to get config
                    String queueName = ((String)record.get('OwnerId')).startsWith('00G') ? 
                                        queueIdNameMap.get((Id)record.get('OwnerId')) : 
                                        recordIdQueueNameMap.get(record.Id);
                    //validate queue name
                    if (String.isNotBlank(queueName) && queueNameToConfig.containsKey(queueName)) {
                        //get round robin assignment config
                        RecordAssignConfiguration__c config = queueNameToConfig.get(queueName);
                        //get next assignee and set as lead owner
                        if (!config.RecordAssignMembers__r.isEmpty()) {
                            //get routing index
                            Integer queueIndex = 0;
                            if (queueNameToRouteIndex.containsKey(config.Queue_Name__c)) {
                                queueIndex = queueNameToRouteIndex.get(config.Queue_Name__c);
                            }

                            //get/set Loan Team
                            LLC_BI__LoanTeam__c teamMember = new LLC_BI__LoanTeam__c();
                            RecordAssignMember__c assignee = config.RecordAssignMembers__r[Math.mod(queueIndex, config.RecordAssignMembers__r.size())];
                            teamMember.LLC_BI__Assigned_Role__c = recordIdRoleIdMap.get(record.Id);
                            teamMember.LLC_BI__User__c = assignee.User__c;
                            teamMember.LLC_BI__Loan__c = record.Id;
                            assignee.Last_Assignment__c = Datetime.now();
                            assignee.Records_Assigned__c = assignee.Records_Assigned__c == null ? 1 : assignee.Records_Assigned__c+1;
                            userIdToMember.put(assignee.User__c, assignee);
                            recordsToCreate.add(teamMember);

                            //increment routing index
                            queueNameToRouteIndex.put(config.Queue_Name__c, ++queueIndex);
                        }
                    }
                }

                //perform updates of ownership and member configs
                insert recordsToCreate;
                update userIdToMember.values();
            }
        }
    }

    /**
     * Process/Reset Member Limits
     */
    private static void processMemberLimits() {
        List<RecordAssignMember__c> membersToUpdate = new List<RecordAssignMember__c>();
        List<RecordAssignMember__c> membersToProcess = [
            SELECT Id, Limit_Frequency__c, Last_Assignment__c
            FROM RecordAssignMember__c 
            WHERE Under_Limit__c = false
        ];

        for (RecordAssignMember__c member : membersToProcess) {
            Datetime compareDate;
            switch on member.Limit_Frequency__c {
                when 'Daily' {
                    compareDate = DateTime.now().addDays(-1);
                }
                when 'Weekly' {
                    compareDate = DateTime.now().addDays(-7);
                }
                when 'Monthly' {
                    compareDate = DateTime.now().addMonths(-1);
                }
                when 'Quarterly' {
                    compareDate = DateTime.now().addMonths(-3);
                }
                when 'Annual' {
                    compareDate = DateTime.now().addYears(-1);
                }
            }
            if (compareDate != null && member.Last_Assignment__c < compareDate) {
                member.Records_Assigned__c = 0;
                membersToUpdate.add(member);
            }
        }

        update membersToUpdate;
    }

    global class AssignmentRequest {
        @InvocableVariable(label='Record Id' required=true description='Id of record to assign ownership via round robin')
        global Id recordId;

        @InvocableVariable(label='Queue Name' description='Use specific Round Robin Configuration record with matching Queue Name')
        global String queueName;
        
        @InvocableVariable(label='Team Role' description='Use Team Member Role Name')
        global Id teamRole;

        global AssignmentRequest() {}

        public AssignmentRequest(Id recordId) {
            this.recordId = recordId;
        }
        
        public AssignmentRequest(Id recordId, String queueName, Id teamRole) {
            this.recordId = recordId;
            this.queueName = queueName;
            this.teamRole = teamRole;
        }
    }
}